
# BannedItem List by IDs
bannedItemId:
  - '4484'
  - '4483'
  - '153'
  - '129'
  - '73'
  - '56'
  - '21'
  - '16'
  - '14'
  - '15'
  - '4111:1'
  - '4111:2'
  - '4111:3'
  - '4111:4'

# Messages
Message-1: "§b[Snowk]§e模式扫描仪难以拆解不纯的原矿石，请冶炼后再进行复制"